// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDDRz4cWFMemDYVl4jzyHkn-18RG_vOY',
    appId: '1:211498980084:web:143d9ca1363981e91f44a1',
    messagingSenderId: '211498980084',
    projectId: 'aldian-firebase',
    authDomain: 'aldian-firebase.firebaseapp.com',
    storageBucket: 'aldian-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQMrfkmJV1ELg4iyHiCodkW4pkdxnw5Q',
    appId: '1:211498980084:android:59051e3e10e41ac21f44a1',
    messagingSenderId: '211498980084',
    projectId: 'aldian-firebase',
    storageBucket: 'aldian-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLV8zq3gOzMTquebJl9YccakViyRvlvY',
    appId: '1:211498980084:ios:4abd33d807cb0d791f44a1',
    messagingSenderId: '211498980084',
    projectId: 'aldian-firebase',
    storageBucket: 'aldian-firebase.appspot.com',
    iosClientId: '211498980084-885nuntrpdfhcdrh8afh8q3s2g072mqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.aldianFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtLV8zq3gOzMTquebJl9YccakViyRvlvY',
    appId: '1:211498980084:ios:4abd33d807cb0d791f44a1',
    messagingSenderId: '211498980084',
    projectId: 'aldian-firebase',
    storageBucket: 'aldian-firebase.appspot.com',
    iosClientId: '211498980084-885nuntrpdfhcdrh8afh8q3s2g072mqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.aldianFb',
  );
}
